// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVGHFCAPvDg6OGTwfZIYoz9OGtWBUhc0',
    appId: '1:445704597964:web:900d671b266a53c8eb6d69',
    messagingSenderId: '445704597964',
    projectId: 'flutter-bootstrap-todo-app',
    authDomain: 'flutter-bootstrap-todo-app.firebaseapp.com',
    storageBucket: 'flutter-bootstrap-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkm9HzkeqPEc9BpvmQ96q-fiN1LJqd8-M',
    appId: '1:445704597964:android:8f7bb5dfb2d679f7eb6d69',
    messagingSenderId: '445704597964',
    projectId: 'flutter-bootstrap-todo-app',
    storageBucket: 'flutter-bootstrap-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJ-BENp_weU0fQAAMvgPrWU-LeXWKUhA',
    appId: '1:445704597964:ios:d99f14e3d495cd63eb6d69',
    messagingSenderId: '445704597964',
    projectId: 'flutter-bootstrap-todo-app',
    storageBucket: 'flutter-bootstrap-todo-app.appspot.com',
    iosBundleId: 'com.darwincch.flutterBootstrapTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJ-BENp_weU0fQAAMvgPrWU-LeXWKUhA',
    appId: '1:445704597964:ios:e2f82b48bd3d038ceb6d69',
    messagingSenderId: '445704597964',
    projectId: 'flutter-bootstrap-todo-app',
    storageBucket: 'flutter-bootstrap-todo-app.appspot.com',
    iosBundleId: 'com.darwincch.flutterBootstrapTodoApp.RunnerTests',
  );
}
